[package]
name = "workx-file-system"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
bytes = { workspace = true }
workx-protocol = { workspace = true }
workx-utils-absolute-path = { workspace = true }
workx-utils-path-uri = { workspace = true }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[lib]
test = false
doctest = false
