[package]
edition.workspace = true
license.workspace = true
name = "workx-prompts"
version.workspace = true

[lib]
doctest = false
name = "workx_prompts"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
workx-context-fragments = { workspace = true }
workx-git-utils = { workspace = true }
workx-execpolicy = { workspace = true }
workx-protocol = { workspace = true }
workx-utils-absolute-path = { workspace = true }
workx-utils-template = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
