[package]
edition.workspace = true
license.workspace = true
name = "workx-utils-output-truncation"
version.workspace = true

[lints]
workspace = true

[dependencies]
workx-protocol = { workspace = true }
workx-utils-string = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lib]
doctest = false
