[package]
edition.workspace = true
license.workspace = true
name = "workx-guardian-context"
version.workspace = true

[lib]
doctest = false
name = "workx_guardian_context"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
workx-protocol = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
