[package]
name = "workx-exec-server-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "workx_exec_server_protocol"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
base64 = { workspace = true }
workx-file-system = { workspace = true }
workx-network-proxy = { workspace = true }
workx-protocol = { workspace = true }
workx-shell-command = { workspace = true }
workx-utils-path-uri = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["arbitrary_precision", "raw_value"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
