[package]
edition.workspace = true
license.workspace = true
name = "workx-analytics"
version.workspace = true

[lib]
doctest = false
name = "workx_analytics"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
workx-app-server-protocol = { workspace = true }
workx-git-utils = { workspace = true }
workx-login = { workspace = true }
workx-model-provider = { workspace = true }
workx-plugin = { workspace = true }
workx-protocol = { workspace = true }
workx-state = { workspace = true }
os_info = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha1 = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
] }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
workx-utils-absolute-path = { workspace = true }
pretty_assertions = { workspace = true }
